### ISSUE TITLE
panic: not found errorcorrectionlevel and mask

### ISSUE THREAD

**Issue by beikege** [tuotoo/qrcode#1]
使用其他网站在线解码正常.

![1](https://user-images.githubusercontent.com/9634079/29632893-f30e0516-8876-11e7-93b6-6eed221a3ad6.png)
```
panic: not found errorcorrectionlevel and mask

goroutine 1 [running]:
github.com/tuotoo/qrcode.(*Matrix).FormatInfo(0xc04209c370, 0x0, 0x1a)
	F:/golang/get/src/github.com/tuotoo/qrcode/qrcode.go:78 +0x232
github.com/tuotoo/qrcode.Decode(0x7dafe0, 0xc042a18500, 0x63067e, 0x3, 0x630438)
	F:/golang/get/src/github.com/tuotoo/qrcode/qrcode.go:879 +0x19f
main.main()
	F:/golang/my/src/qr/mian.go:114 +0x676
```

**Comment by craftsman-li** [comment]
解决了没？？？

**Comment by yuanpengchao** [comment]
遇到了同样的问题 not found error correction level and mask

**Comment by this-BaiShi** [comment]
同问题+1

**Comment by orefalo** [comment]
same issue

**Comment by blusewang** [comment]
use https://github.com/makiuchi-d/gozxing to fix it!
